### ISSUE TITLE
Issues with robot description parse

### ISSUE THREAD

**Issue by Engietoday** [unitreerobotics/laikago_ros#1]
Hello

I have followed the steps in READ_ME.md but running into issues when trying to launch rviz.launch inside of laikago_rviz package. I' m getting the following error messages. 

`[ERROR] [1561787437.444252717]: Geometry tag contains no child element.
[ERROR] [1561787437.444288480]: Could not parse visual element for Link [FL_thigh]
[ERROR] [1561787437.444336866]: Geometry tag contains no child element.
[ERROR] [1561787437.444346211]: Could not parse visual element for Link [FR_thigh]
[ERROR] [1561787437.444389953]: Geometry tag contains no child element.
[ERROR] [1561787437.444399517]: Could not parse visual element for Link [RR_thigh]
[ERROR] [1561787437.444440450]: Geometry tag contains no child element.
[ERROR] [1561787437.444448261]: Could not parse visual element for Link [RL_thigh]
[ERROR] [1561787437.444490167]: Joint [FL_hip_joint] is of type REVOLUTE but it does not specify limits
[ERROR] [1561787437.444508022]: joint xml is not initialized correctly
[ INFO] [1561787437.524283215]: rviz version 1.13.3
[ INFO] [1561787437.524330877]: compiled against Qt version 5.9.5
[ INFO] [1561787437.524342805]: compiled against OGRE version 1.9.0 (Ghadamon)
[robot_state_publisher-3] process has died [pid 12701, exit code 255, cmd /opt/ros/melodic/lib/robot_state_publisher/state_publisher __name:=robot_state_publisher __log:=/home/prismadynamics/.ros/log/d133b462-9a31-11e9-9df2-38dead2d76c5/robot_state_publisher-3.log].
log file: /home/prismadynamics/.ros/log/d133b462-9a31-11e9-9df2-38dead2d76c5/robot_state_publisher-3*.log
[WARN] [1561787437.780960]: FL_hip_joint is not fixed, nor continuous, but limits are not specified!
[WARN] [1561787437.782019]: FR_hip_joint is not fixed, nor continuous, but limits are not specified!
[WARN] [1561787437.782682]: RR_hip_joint is not fixed, nor continuous, but limits are not specified!
[WARN] [1561787437.783340]: RL_hip_joint is not fixed, nor continuous, but limits are not specified!
`

**Comment by Engietoday** [comment]
One thing I have also noticed is many parameters, for example hip_torque_max, in leg.xacro are not defined anywhere. Could that be an issue?

**Comment by TrivasZhang** [comment]
Hi, @Engietoday 

Sorry for my late reply. 
We made a new commit now. Please try if it works.
Thanks for your report.

**Comment by Engietoday** [comment]
I pulled the new commit and tested it on both Ubuntu 16 and 18 (my original computer).
It works with Ubuntu 16 and ROS Kinetic but I still get the same errors with Ubuntu 18 and its ROS version.

**Comment by TrivasZhang** [comment]
I'm sorry. The Ubuntu18 is too new. 
Though it will be supported in the future, but I'm not sure when we have the time to solve this.

**Comment by milyasmeo** [comment]
Hi, Im using Ubunutu 18.04 & ROS melodic. I ran : $ " roslaunch aliengo_description aliengo_rviz.launch  "
but it gave error: " [ERROR] [1593505924.912405846]: Geometry tag contains no child element.
[ERROR] [1593505924.912966182]: Could not parse visual element for Link [FR_thigh]
[ERROR] [1593505924.913143052]: Geometry tag contains no child element.
[ERROR] [1593505924.913155123]: Could not parse visual element for Link [FL_thigh]
[ERROR] [1593505924.913283436]: Geometry tag contains no child element.
[ERROR] [1593505924.913292727]: Could not parse visual element for Link [RR_thigh]
[ERROR] [1593505924.913421811]: Geometry tag contains no child element.
[ERROR] [1593505924.913430520]: Could not parse visual element for Link [RL_thigh]
[ERROR] [1593505924.913541734]: Joint [FR_hip_joint] is of type REVOLUTE but it does not specify limits
[ERROR] [1593505924.913550989]: joint xml is not initialized correctly
[ INFO] [1593505924.986210382]: rviz version 1.13.12
[ INFO] [1593505924.986274520]: compiled against Qt version 5.9.5
[ INFO] [1593505924.986284716]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1593505924.989270822]: Forcing OpenGl version 0.
[ INFO] [1593505925.070564158]: Stereo is NOT SUPPORTED
[ INFO] [1593505925.070627544]: OpenGl version: 3 (GLSL 1.3).
[robot_state_publisher-3] process has died [pid 18423, exit code 1, cmd /opt/ros/melodic/lib/robot_state_publisher/robot_state_publisher __name:=robot_state_publisher __log:=/home/ilyas03/.ros/log/2ceb99b4-baac-11ea-93c8-50e085bc1c0e/robot_state_publisher-3.log].
log file: /home/ilyas03/.ros/log/2ceb99b4-baac-11ea-93c8-50e085bc1c0e/robot_state_publisher-3*.log
[ERROR] [1593505925.115930073]: Geometry tag contains no child element.
[ERROR] [1593505925.115951932]: Could not parse visual element for Link [FR_thigh]
[ERROR] [1593505925.116039377]: Geometry tag contains no child element.
[ERROR] [1593505925.116048602]: Could not parse visual element for Link [FL_thigh]
[ERROR] [1593505925.116131643]: Geometry tag contains no child element.
[ERROR] [1593505925.116139936]: Could not parse visual element for Link [RR_thigh]
[ERROR] [1593505925.116222812]: Geometry tag contains no child element.
[ERROR] [1593505925.116231469]: Could not parse visual element for Link [RL_thigh]
[ERROR] [1593505925.116297092]: Joint [FR_hip_joint] is of type REVOLUTE but it does not specify limits
[ERROR] [1593505925.116305661]: joint xml is not initialized correctly ".

We have recetly purchased AlienGo in NTU , Singapore. Please provide updated Repository to Run AlienGo robot.
Dr Muhammad Ilyas (NTU) :  +65 90564435
