### ISSUE TITLE
add_dependencies needed in CMakeLists.txt file [Bug]

### ISSUE THREAD

**Issue by JaehyunShim** [unitreerobotics/laikago_ros#2]
Hi,

There are two lines that have to be added in CMakeLists.txt files as below.

```sh
add_dependencies(laikago_joint_controller laikago_msgs_gencpp)
```
after [this line](https://github.com/unitreerobotics/laikago_ros/blob/master/laikago_controller/CMakeLists.txt#L28) and

```sh
add_dependencies(${PROJECT_NAME} laikago_msgs_gencpp)
```
after [this line](https://github.com/unitreerobotics/laikago_ros/blob/master/laikago_gazebo/CMakeLists.txt#L35).

A simple way of checking this bug is to remove ~/catkin_ws/build and ~/catkin_ws/devel directories and catkin_make again, then you will see a compile crash. By adding add_dependencies() lines, your code will compile dependency packages first and compile the controller and gazebo packages and avoid the compile crash.

Ryan

**Comment by TrivasZhang** [comment]
Yes, these lines are needed. Thanks for your contribution!
