### ISSUE TITLE
Laikago unable to stand in Gazebo7

### ISSUE THREAD

**Issue by waiyc** [unitreerobotics/laikago_ros#3]
Hi,
I do note that Gazebo8 is required but I manage to make it launch in Gazebo7.
However,the laikago is unable to stand when I run laikago_servo node.
The motors on the right side seems to be slower than the motors on the left. 
It is because I am using Gazebo7?

**Comment by TrivasZhang** [comment]
Gazebo offical stable version is 11.0.0. I suggest try new version.
